# Copyright 2023 HM Revenue & Customs
#

play.filters.headers.contentSecurityPolicy = "default-src 'self' 'unsafe-eval' 'unsafe-inline' localhost:9032 https://*.google-analytics.com https://*.googletagmanager.com https://*.optimizely.com https://optimizely.s3.amazonaws.com data:"

controllers.controllers.internal.PlatformHealthCheckController.needsAuditing = false

assets {
  version = "2.241.0"
  version = ${?ASSETS_FRONTEND_VERSION}
  url = "http://localhost:9032/assets/"
}

preferences-frontend.host = "http://localhost:9024"
yta.host = "http://localhost:9020"
company-auth.host = "http://localhost:9025"
activation.gracePeriodInMin=5

portal {
  tokenTimeout = 240
  redirectDomainAllowlist = [
    localhost
  ]
}
